const $=s=>document.querySelector(s),app=$('#app');let shop=null,cart={product:null,duration:null,qty:1},token=localStorage.getItem('nx_admin');
async function api(url,opt={}){const h=opt.headers||{};if(token)h.Authorization='Bearer '+token;opt.headers=h;const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Terjadi kesalahan');return d}
function rupiah(n){return 'Rp'+Number(n||0).toLocaleString('id-ID')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadShop(){shop=await api('/api/shop');renderHome()}
function renderHome(){app.innerHTML=`<header class="top"><nav class="nav"><div class="brand"><img src="/logo.jpg"><span>NIKXITER SHOP</span></div><button class="btn" onclick="location.hash='status'">🔎 Cek Pesanan</button></nav></header><main class="wrap"><section class="hero"><img src="/logo.jpg"></section><div class="row" style="justify-content:space-between;margin:12px 0 16px"><div><h1 style="margin:0">🛒 Pilih Produk</h1><p class="muted">Fast • Safe • Admin Amanah</p></div><button class="btn primary" onclick="location.hash='admin'">🔐 Admin</button></div><div class="grid">${Object.entries(shop.products).map(([code,p])=>productCard(code,p)).join('')}</div></main>`}
function productCard(code,p){const durations=Object.entries(p.prices);const first=durations[0];const stock=first?(p.stock[first[0]]||[]).length:0;return `<article class="card product"><span class="tag">${p.status==='ready'?'🟢 ON':p.status==='maintenance'?'🟡 MAINTENANCE':'🔴 PATCH'}</span><h3>${esc(p.name)}</h3><p class="muted">${durations.length} pilihan durasi • Stok total ${Object.values(p.stock).reduce((a,x)=>a+x.length,0)} key</p><div class="price">${rupiah(first?.[1])}</div><div class="muted">mulai dari</div><button class="btn primary" style="width:100%;margin-top:14px" onclick="choose('${code}')">Pilih Produk</button></article>`}
function choose(code){const p=shop.products[code];if(p.status!=='ready')return alert('Produk sedang '+p.status);cart={product:code,duration:Object.keys(p.prices)[0],qty:1};renderCheckout()}
function renderCheckout(){const p=shop.products[cart.product];app.innerHTML=`<header class="top"><nav class="nav"><div class="brand"><img src="/logo.jpg">NIKXITER SHOP</div><button class="btn" onclick="renderHome()">← Kembali</button></nav></header><main class="wrap"><div class="card"><h2>${esc(p.name)}</h2><div class="form"><div class="field"><label>Durasi</label><select onchange="cart.duration=this.value;renderCheckout()">${Object.entries(p.prices).map(([d,v])=>`<option value="${esc(d)}" ${d===cart.duration?'selected':''}>${esc(d)} — ${rupiah(v)} — stok ${(p.stock[d]||[]).length}</option>`).join('')}</select></div><div class="field"><label>Jumlah key</label><div class="qty"><button class="btn" onclick="cart.qty=Math.max(1,cart.qty-1);renderCheckout()">−</button><b>${cart.qty}</b><button class="btn" onclick="cart.qty=Math.min(10,cart.qty+1);renderCheckout()">+</button></div></div><div class="notice"><b>Total: ${rupiah(p.prices[cart.duration]*cart.qty)}</b><br><span class="muted">Maksimal 10 key per order.</span></div><button class="btn primary" onclick="createOrderForm()">💳 Lanjut Pembayaran</button></div></div></main>`}
function createOrderForm(){const p=shop.products[cart.product],avail=(p.stock[cart.duration]||[]).length;if(avail<cart.qty)return alert('Stok tidak cukup. Tersedia '+avail+' key.');app.innerHTML=`<main class="wrap"><div class="card" style="max-width:620px;margin:40px auto"><h2>📱 Data Pembeli</h2><p class="muted">${esc(p.name)} • ${esc(cart.duration)} • ${cart.qty} key</p><div class="form"><div class="field"><label>Nama</label><input id="name" placeholder="Nama kamu"></div><div class="field"><label>WhatsApp</label><input id="wa" placeholder="085xxxxxxxxx"></div><button class="btn primary" onclick="submitOrder()">Buat Pesanan</button><button class="btn" onclick="renderCheckout()">Kembali</button></div></div></main>`}
async function submitOrder(){try{const fd=new FormData();fd.append('product',cart.product);fd.append('duration',cart.duration);fd.append('quantity',cart.qty);fd.append('name',$('#name').value);fd.append('whatsapp',$('#wa').value);const d=await fetch('/api/orders',{method:'POST',body:fd}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);return x});renderPayment(d.order)}catch(e){alert(e.message)}}
function renderPayment(o){app.innerHTML=`<header class="top"><nav class="nav"><div class="brand"><img src="/logo.jpg">NIKXITER SHOP</div></nav></header><main class="wrap"><div class="card" style="max-width:650px;margin:24px auto;text-align:center"><h2>💳 Pembayaran</h2><p>ID Pembayaran: <b>${esc(o.paymentId)}</b></p><img src="/qris.jpg" style="width:min(100%,500px);border-radius:14px"><div class="notice" style="text-align:left;margin-top:14px"><b>${esc(o.product)}</b><br>${esc(o.duration)} × ${o.quantity}<br>Total <strong>${rupiah(o.total)}</strong><br>Bayar ke <b>NIKXITER</b> via QRIS.</div><div class="form" style="text-align:left;margin-top:14px"><div class="field"><label>Upload bukti transfer (JPG/PNG/WEBP, max 8 MB)</label><input id="proof" type="file" accept="image/jpeg,image/png,image/webp"></div><button class="btn primary" onclick="sendProof('${o.paymentId}')">📸 Kirim Bukti Pembayaran</button><button class="btn" onclick="location.hash='status';renderStatus('${o.paymentId}')">🔎 Cek Status</button></div></div></main>`}
async function sendProof(id){try{const f=$('#proof').files[0];if(!f)return alert('Pilih bukti pembayaran dulu.');const fd=new FormData();fd.append('proof',f);const d=await fetch('/api/orders/'+id+'/proof',{method:'POST',body:fd}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error);return x});alert('Bukti berhasil dikirim. Tunggu verifikasi admin.');renderStatus(id)}catch(e){alert(e.message)}}
async function renderStatus(id){try{const o=await api('/api/orders/'+id);app.innerHTML=`<main class="wrap"><div class="card" style="max-width:650px;margin:40px auto"><h2>🧾 Status Pesanan</h2><p>ID: <b>${esc(o.paymentId)}</b></p><p>Produk: ${esc(o.product)}<br>Durasi: ${esc(o.duration)}<br>Jumlah: ${o.quantity}<br>Total: <b>${rupiah(o.total)}</b></p><div class="notice">Status: <b>${esc(o.status)}</b></div>${o.keys?.length?'<div class="notice" style="margin-top:12px">🔑 Key kamu:<br>'+o.keys.map(k=>'<code>'+esc(k)+'</code>').join('<br>')+'</div>':''}<button class="btn" style="margin-top:14px" onclick="renderHome()">Kembali ke Toko</button></div></main>`}catch(e){app.innerHTML=`<main class="wrap"><div class="card"><h2>🔎 Cek Pesanan</h2><input id="oid" placeholder="NX-XXXXXX"><button class="btn primary" style="margin-top:10px" onclick="renderStatus($('#oid').value.trim())">Cek</button></div></main>`}}
function login(){app.innerHTML=`<main class="wrap"><div class="card" style="max-width:420px;margin:70px auto"><h2>🔐 PANEL ADMIN</h2><div class="form"><input id="au" placeholder="Username"><input id="ap" type="password" placeholder="Password"><button class="btn primary" onclick="doLogin()">Login</button><button class="btn" onclick="renderHome()">Kembali</button></div></div></main>`}
async function doLogin(){try{const d=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#au').value,password:$('#ap').value})});token=d.token;localStorage.setItem('nx_admin',token);renderAdmin()}catch(e){alert(e.message)}}
let adminTimer=null,lastPending=0;async function renderAdmin(){try{const d=await api('/api/admin/dashboard');app.innerHTML=`<header class="top"><nav class="nav"><div class="brand"><img src="/logo.jpg">NIKXITER ADMIN</div><div class="row"><span id="notif" class="tag">🔔 ${d.pendingCount} pending</span><button class="btn" onclick="logout()">Logout</button></div></nav></header><div class="admin"><aside class="side"><button class="btn" onclick="adminHome()">📊 Dashboard</button><button class="btn" onclick="adminProducts()">📦 Status Produk</button><button class="btn" onclick="adminPrices()">💰 Atur Harga</button><button class="btn" onclick="adminManage()">🛠 Kelola Produk</button><button class="btn" onclick="toggleBot()">${d.botStatus==='aktif'?'🔴 Matikan Bot':'🟢 Hidupkan Bot'}</button><button class="btn" onclick="adminOrders()">📊 Order</button><button class="btn" onclick="adminStock()">📦 Restock Key</button></aside><section class="main" id="adminmain"></section></div>`;lastPending=d.pendingCount;adminHome();clearInterval(adminTimer);adminTimer=setInterval(refreshNotif,5000)}catch(e){token=null;localStorage.removeItem('nx_admin');login()}}
async function refreshNotif(){try{const d=await api('/api/admin/dashboard');const el=$('#notif');if(el)el.textContent='🔔 '+d.pendingCount+' pending';if(d.pendingCount>lastPending&&'Notification'in window){if(Notification.permission==='granted')new Notification('NIKXITER SHOP',{body:'Ada bukti pembayaran baru yang perlu diverifikasi.'});else Notification.requestPermission()}if(d.pendingCount>lastPending&&navigator.vibrate)navigator.vibrate([150,80,150]);lastPending=d.pendingCount}catch{}}
function adminHome(){api('/api/admin/dashboard').then(d=>{$('#adminmain').innerHTML=`<h1>Dashboard</h1><div class="stats"><div class="card stat"><span class="muted">Total Order</span><br><strong>${d.orders.length}</strong></div><div class="card stat"><span class="muted">Menunggu Verifikasi</span><br><strong class="gold">${d.pendingCount}</strong></div><div class="card stat"><span class="muted">Status Toko</span><br><strong>${d.botStatus}</strong></div><div class="card stat"><span class="muted">Produk</span><br><strong>${Object.keys(d.products).length}</strong></div></div><h2>🚨 Bukti Terbaru</h2><div class="grid">${d.orders.filter(o=>o.status==='bukti diterima - menunggu verifikasi').slice(0,8).map(orderAdminCard).join('')||'<div class="card muted">Belum ada bukti pembayaran baru.</div>'}</div>`})}
function orderAdminCard(o){return `<article class="card order pending"><div class="row" style="justify-content:space-between"><b>${esc(o.paymentId)}</b><span class="tag">MENUNGGU VERIFIKASI</span></div><div>${esc(o.product)}<br>${esc(o.duration)} × ${o.quantity}<br><b>${rupiah(o.total)}</b><br>WA: ${esc(o.whatsapp)}</div>${o.proof?`<img class="proof" src="/uploads/${encodeURIComponent(o.proof)}">`:''}<div class="row"><button class="btn primary" onclick="approve('${o.paymentId}')">✅ SETUJUI</button><button class="btn" onclick="rejectO('${o.paymentId}')">❌ TOLAK</button></div></article>`}
async function approve(id){if(!confirm('Setujui pembayaran dan keluarkan key dari stok?'))return;try{const d=await api('/api/admin/orders/'+id+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});alert('Disetujui. Key: '+d.keys.join(', '));adminHome()}catch(e){alert(e.message)}}
async function rejectO(id){if(!confirm('Tolak pembayaran ini?'))return;try{await api('/api/admin/orders/'+id+'/reject',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});adminHome()}catch(e){alert(e.message)}}
async function adminOrders(){const d=await api('/api/admin/dashboard');$('#adminmain').innerHTML=`<h1>📊 Order</h1><div class="card" style="overflow:auto"><table class="table"><thead><tr><th>ID</th><th>Produk</th><th>Total</th><th>Pembeli</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${d.orders.map(o=>`<tr><td><b>${esc(o.paymentId)}</b><br><small>${new Date(o.createdAt).toLocaleString('id-ID')}</small></td><td>${esc(o.product)}<br>${esc(o.duration)} × ${o.quantity}</td><td>${rupiah(o.total)}</td><td>${esc(o.name)}<br>${esc(o.whatsapp)}</td><td>${esc(o.status)}</td><td>${o.proof?`<button class="btn" onclick="viewProof('${o.paymentId}')">👁 Bukti</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
async function viewProof(id){const o=await api('/api/orders/'+id);app.insertAdjacentHTML('beforeend',`<div class="modal" onclick="this.remove()"><div class="box card" onclick="event.stopPropagation()"><h3>${esc(o.paymentId)} — Bukti Pembayaran</h3><img class="proof" src="${o.proofUrl}"><div class="row" style="margin-top:12px"><button class="btn primary" onclick="approve('${o.paymentId}');this.closest('.modal').remove()">✅ Setujui</button><button class="btn" onclick="rejectO('${o.paymentId}');this.closest('.modal').remove()">❌ Tolak</button></div></div></div>`)}
async function adminProducts(){const d=await api('/api/admin/dashboard');$('#adminmain').innerHTML=`<h1>📦 Status Produk</h1><div class="grid">${Object.entries(d.products).map(([c,p])=>`<div class="card"><h3>${esc(p.name)}</h3><select onchange="setStatus('${c}',this.value)"><option value="ready" ${p.status==='ready'?'selected':''}>🟢 ON</option><option value="maintenance" ${p.status==='maintenance'?'selected':''}>🟡 MAINTENANCE</option><option value="patch" ${p.status==='patch'?'selected':''}>🔴 PATCH</option></select></div>`).join('')}</div>`}
async function setStatus(c,s){await api('/api/admin/products/'+c+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s})})}
async function adminPrices(){const d=await api('/api/admin/dashboard');$('#adminmain').innerHTML=`<h1>💰 Atur Harga</h1>${Object.entries(d.products).map(([c,p])=>`<div class="card" style="margin-bottom:12px"><h3>${esc(p.name)}</h3>${Object.entries(p.prices).map(([dur,price])=>`<div class="row" style="margin:8px 0"><span style="min-width:100px">${esc(dur)}</span><input id="price-${c}-${dur.replaceAll(' ','_')}" value="${price}" type="number"><button class="btn" onclick="savePrice('${c}','${esc(dur)}','price-${c}-${dur.replaceAll(' ','_')}')">Simpan</button></div>`).join('')}</div>`).join('')}`}
async function savePrice(c,d,id){await api('/api/admin/products/'+c+'/price',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({duration:d,price:Number($('#'+id).value)})});alert('Harga disimpan')}
async function adminStock(){const d=await api('/api/admin/dashboard');$('#adminmain').innerHTML=`<h1>📦 Restock Key</h1>${Object.entries(d.products).map(([c,p])=>`<div class="card" style="margin-bottom:12px"><h3>${esc(p.name)}</h3><select id="dur-${c}">${Object.keys(p.prices).map(x=>`<option>${esc(x)}</option>`).join('')}</select><textarea id="keys-${c}" rows="5" placeholder="Satu key per baris atau format Key: 12345"></textarea><button class="btn primary" onclick="restock('${c}')">Tambah Stok</button><p class="muted">${Object.entries(p.stock).map(([x,a])=>esc(x)+': '+a.length+' key').join(' • ')}</p></div>`).join('')}`}
async function restock(c){const dur=$('#dur-'+c).value,keys=$('#keys-'+c).value;const d=await api('/api/admin/products/'+c+'/restock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({duration:dur,keys})});alert('Restock berhasil: +'+d.added+' key')}
function adminManage(){api('/api/admin/dashboard').then(d=>{$('#adminmain').innerHTML=`<h1>🛠 Kelola Produk</h1><div class="card"><h3>Tambah Produk</h3><p class="muted">Format harga JSON, contoh: {"1 Hari":10000,"7 Hari":50000}</p><div class="form"><input id="newcode" placeholder="kode-produk"><input id="newname" placeholder="Nama Produk"><input id="newprices" placeholder='{"1 Hari":10000,"7 Hari":50000}'><button class="btn primary" onclick="addProduct()">Tambah</button></div></div>${Object.entries(d.products).map(([c,p])=>`<div class="card" style="margin-top:12px"><b>${esc(p.name)}</b><div class="row" style="margin-top:10px"><button class="btn" onclick="renameP('${c}','${esc(p.name)}')">✏️ Ubah Nama</button><button class="btn" onclick="deleteP('${c}')">🗑 Hapus</button></div></div>`).join('')}`})}
async function addProduct(){try{await api('/api/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:$('#newcode').value.trim(),name:$('#newname').value.trim(),prices:JSON.parse($('#newprices').value)})});adminManage()}catch(e){alert(e.message)}}
async function renameP(c,n){const v=prompt('Nama baru',n);if(v)await api('/api/admin/products/'+c+'/rename',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:v})});adminManage()}
async function deleteP(c){if(confirm('Hapus produk?')){await api('/api/admin/products/'+c,{method:'DELETE'});adminManage()}}
async function toggleBot(){await api('/api/admin/toggle-bot',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});renderAdmin()}
async function logout(){await api('/api/logout',{method:'POST'}).catch(()=>{});token=null;localStorage.removeItem('nx_admin');clearInterval(adminTimer);renderHome()}
window.addEventListener('hashchange',()=>{const h=location.hash.slice(1);if(h==='admin')login();else if(h==='status')renderStatus();});
loadShop();
